-- Shared temple CMS foundation for Supabase.
-- Run this in Supabase SQL Editor before using shared uploads.

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  category text,
  image_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.site_content (
  id text primary key,
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'site_content'
  ) then
    alter publication supabase_realtime add table public.site_content;
  end if;
end
$$;

alter table public.site_content enable row level security;

drop policy if exists "Public site content read access" on public.site_content;
drop policy if exists "Authenticated site content insert access" on public.site_content;
drop policy if exists "Authenticated site content update access" on public.site_content;

create policy "Public site content read access"
on public.site_content for select
to anon, authenticated
using (true);

create policy "Authenticated site content insert access"
on public.site_content for insert
to authenticated
with check (true);

create policy "Authenticated site content update access"
on public.site_content for update
to authenticated
using (true)
with check (true);

alter table public.gallery enable row level security;

drop policy if exists "Public gallery read access" on public.gallery;
drop policy if exists "Authenticated gallery insert access" on public.gallery;
drop policy if exists "Authenticated gallery update access" on public.gallery;
drop policy if exists "Authenticated gallery delete access" on public.gallery;

create policy "Public gallery read access"
on public.gallery for select
to anon, authenticated
using (true);

create policy "Authenticated gallery insert access"
on public.gallery for insert
to authenticated
with check (true);

create policy "Authenticated gallery update access"
on public.gallery for update
to authenticated
using (true)
with check (true);

create policy "Authenticated gallery delete access"
on public.gallery for delete
to authenticated
using (true);

insert into storage.buckets (id, name, public)
values ('temple-media', 'temple-media', true)
on conflict (id) do nothing;

drop policy if exists "Public temple media read access" on storage.objects;
drop policy if exists "Authenticated temple media upload access" on storage.objects;
drop policy if exists "Authenticated temple media update access" on storage.objects;
drop policy if exists "Authenticated temple media delete access" on storage.objects;

create policy "Public temple media read access"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'temple-media');

create policy "Authenticated temple media upload access"
on storage.objects for insert
to authenticated
with check (bucket_id = 'temple-media');

create policy "Authenticated temple media update access"
on storage.objects for update
to authenticated
using (bucket_id = 'temple-media')
with check (bucket_id = 'temple-media');

create policy "Authenticated temple media delete access"
on storage.objects for delete
to authenticated
using (bucket_id = 'temple-media');
